#!/usr/bin/env python3
"""Generate compressed web interface assets.

This script compresses ``index.html`` using Brotli (widely supported by
modern browsers) and writes ``WebInterfaceHtml.h`` with a PROGMEM byte array
that can be served with a ``Content-Encoding: br`` response header.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

import brotli

ROOT = Path(__file__).resolve().parent
INDEX_HTML = ROOT / "index.html"
OUTPUT_HEADER = ROOT / "WebInterfaceHtml.h"


def format_byte_array(data: bytes, indent: int = 2, line_width: int = 80) -> str:
    prefix = " " * indent
    items = [str(b) for b in data]
    lines = []
    current = []
    current_len = 0

    for item in items:
        item_len = len(item) + 2  # account for comma and space
        if current and current_len + item_len > max(line_width - indent, 10):
            lines.append(prefix + ", ".join(current))
            current = [item]
            current_len = item_len
        else:
            current.append(item)
            current_len += item_len

    if current:
        lines.append(prefix + ", ".join(current))

    return ",\n".join(lines)


def generate() -> None:
    if not INDEX_HTML.exists():
        raise SystemExit(f"Missing {INDEX_HTML}")

    html = INDEX_HTML.read_bytes()
    compressed = brotli.compress(html, quality=11, mode=brotli.MODE_TEXT)

    array_body = format_byte_array(compressed)
    header = f"""#pragma once

#include <pgmspace.h>
#include <stddef.h>
#include <stdint.h>

namespace interface {{

// Auto-generated by generate_web_interface.py. Do not edit manually.
static const size_t kWebInterfaceHtmlBrotliLength = {len(compressed)};
static const uint8_t kWebInterfaceHtmlBrotli[] PROGMEM = {{
{array_body}
}};

}}  // namespace interface
"""

    OUTPUT_HEADER.write_text(header)
    print(
        textwrap.dedent(
            f"""
            Wrote {OUTPUT_HEADER}.
              Source: {INDEX_HTML.name} ({len(html)} bytes)
              Compressed (brotli): {len(compressed)} bytes
            """
        ).strip()
    )


if __name__ == "__main__":
    generate()
